builders:
  method_extractor_generator:
    import: "package:method_extractor_generator/builder.dart"
    builder_factories: ["methodExtractorBuilder"]
    build_extensions: {".dart": [".method.gen.json"]}
    auto_apply: dependents
    build_to: cache
