name: method_extractor_generator
description: Extract methods and convert them to json for further processing.
version: 3.1.0
repository: https://github.com/LiewJunTung/Method-Extractor-Generator

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build: 2.4.1
  build_config: 1.1.1
  source_gen: 1.4.0
  method_extractor: 2.1.0
  analyzer: 5.13.0

dev_dependencies:
  test: ^1.24.6
